### ISSUE TITLE
Measure fitness from bones average

### ISSUE THREAD

**Issue by chlorophyll-zz** [keiwando/evolution#2]
Hey @keiwando , 
first thanks for your project. 
I have build a creature that can jump two loops. 
Unfortunately, after generation 90, the creature makes no progress in fitness anymore. 
As i observe the mutated creatures, the farthest traveled joint measures the fitness. 

That motivates the creature, developing to stretch all its muscles, at the end of the evolution time-window, which is counter-productive as it is not evolving to successfully completing two loop jump, but to stretch its muscles. 

So, could you measure the fitness from the average of all the bones, so the farthest average of the joints and not the farthest moved joint -creature becomes parent for mutation? 
That would be great. Thanks in advance for your input on this topic.

**Comment by keiwando** [comment]
Hi!

None of the tasks use only a single joint position in order to determine the fitness of any creature. The position of the creature used in the running task for example is the average of all joint positions. The obstacle jump factors in the maximal height and the duration of contact of any joint with the obstacle.

The jumping task, which is what I think you are referring to, uses a weighted average of the highest joint's and lowest joint's distance from the ground with a weighting ratio of 4 : 1 in favor of the lowest joint (So an actual jump is rewarded higher than just a stretch).

Here's the relevant piece of code:
https://github.com/keiwando/evolution/blob/master/Assets/Scripts/Util/JumpingObjectiveTracker.cs
(Ignore the `maxHeightJumped` field, I just noticed that I had forgotten to remove that from the code. It's not being used for anything.)

I'm absolutely not saying that this is the perfect fitness function in any way, but here are at least some of my reasons for going with this one instead of other possible variants:

* Only using the highest joint's position would purely award tall creatures and creatures that can stretch the furthest. A creature that can jump almost as high as another one can stretch (without jumping at all) would get a lower fitness score, which is not what we want.
* At the start of the simulation when pretty much no creature can jump yet, we need a way to distinguish ones that are showing signs of potential future success, which we can't do if we're only relying on the lowest joint's height above the ground.
* Awarding fitness based on the average position of all joints would assign more fitness to a creature that can't jump but has a higher center of gravity simply based on its joint distribution than another design that can jump but only reaches a lower center of gravity with its jump (e.g. because most of its joints are in the lower half of the body).

The problem with the current fitness function is that if a creature can stretch very far, the fitness can still be thrown off in favor of a stretching behaviour.

It might be interesting to try an extended variant of the current function where all joints are considered, but lower joints drag the average down further than higher joints can drag it up (so an extension of the current weighting process) so that a definitive jump can easily lead to a better score than just a stretch.

**Comment by chlorophyll-zz** [comment]
Thank you for the detailed explanation. Do you want me to leave this open or close?
