### ISSUE TITLE
Have you considered using the NEAT algorithm?

### ISSUE THREAD

**Issue by leshchenko1979** [keiwando/evolution#3]
https://en.m.wikipedia.org/wiki/Neuroevolution_of_augmenting_topologies

The authors claim that the algorithm learns faster.

**Comment by keiwando** [comment]
I have definitely thought about it but it's not trivial to add, since the many parts of the current implementation are based on the fact that the network structure is the same for all creatures throughout the entire simulation.

For example, with a NEAT implementation, it wouldn't make much sense for the user to be able to configure the network size and shape themselves, which I would have to deal with. I would also have to introduce a new serialization version and maintain backwards compatibility etc.

However, I would absolutely expect a NEAT implementation to outperform the current implementation in terms of learning speed.

I might try it out if I find enough time, but it's also not the highest priority item on the TODO list for this project at the moment.
