### ISSUE TITLE
Simulation camera speed is too slow

### ISSUE THREAD

**Issue by Bysmyyr** [keiwando/evolution#6]
Hi, thanks for a great game. I found so fast moving creature so the camera is too slow. Check the picture:

![D8B1D5A0-000C-4C73-8A09-918119611B7E](https://user-images.githubusercontent.com/3306756/103015705-93d3ea00-4549-11eb-8d29-70c08aa7619e.png)

The feature will go completely of the screen...

iPhone xs

**Comment by keiwando** [comment]
Do you have the simulation file by any chance? That would definitely help me reproduce this.

**Comment by Bysmyyr** [comment]
There you go!
[sim.evol.zip](https://github.com/keiwando/evolution/files/5738761/sim.evol.zip)

**Comment by keiwando** [comment]
Sorry about the delay 🙈 I just tried that simulation file and it appears like the creature design has an unconnected joint that immediately falls through the ground. The camera position is calculated as the average of all joints of a creature, so that loose joint will throw off that average. If you delete the loose joint (which you should do anyway since I don't know what other kinds of undefined behaviour you might be getting with it still there) the camera should be following the creature properly.
